# Generated by Django 4.0.5 on 2022-07-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.JSONField()),
            ],
        ),
    ]
