# Generated by Django 4.0.6 on 2022-07-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Playground', '0004_city_country_delete_citymodel_delete_countrymodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country_name',
        ),
    ]
